services:
  ip-extract:
    image: ghcr.io/npcdw/ip-extract
    container_name: ip-extract
    volumes:
      - "${PWD}/data/:/data/"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      IP2LOCATION_TOKEN: 'https://lite.ip2location.com/database-download 中的 Token'
      DOWNLOAD_DIR: '/data'
      UNZIP_DIR: '/data'
      OUTPUT_DIR: '/data'